website/views.py
from flask import (
    Blueprint,
    render_template,
    request,
    flash,
    jsonify,
    send_file,
    redirect,
    url_for,
)
from flask_login import login_required, current_user
from .models import Aircraft, User
from .forms import AircraftForm
from . import w_and_b as wandb
from . import db
import json, io, ast
import matplotlib.pyplot as plt
from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas


views = Blueprint("views", __name__)


@views.route("/", methods=["GET", "POST"])
@login_required
def home():
    form = AircraftForm()
    aircrafts = Aircraft.query.order_by(Aircraft.id).all()

    return render_template(
        "home.html", aircrafts=aircrafts, user=current_user, form=form,
    )


@views.route("/plot")
def plot():
    ac_id = request.args.get("ac_id")
    load_scheme = ast.literal_eval(request.args.get("load_scheme"))
    fuel = float(request.args.get("fuel"))
    fuel_burn = float(request.args.get("fuel_burn"))
    print("LOAD SCHEME FOR PLOT IS TYPE:", type(load_scheme))
    print(load_scheme)
    aircraft = Aircraft.query.filter_by(id=ac_id).first()
    print("AIRCRAFT ID:", ac_id)
    print(list(ast.literal_eval(aircraft.envelope)))
    ac_model = wandb.AircraftModel(
        ac_reg=aircraft.registration,
        type=aircraft.aircraft_type,
        mtow=aircraft.mtow,
        mlw=aircraft.mlw,
        empty_weight=aircraft.empty_weight,
        max_fuel=aircraft.max_fuel,
        fuel_type=aircraft.fuel_type,
        envelope=list(ast.literal_eval(aircraft.envelope)),
        loading_points=ast.literal_eval(aircraft.loading_points),
    )
    load_scheme2 = load_scheme.copy()
    for key in ["ac_id", "fuel", "fuel_burn"]:
        del load_scheme2[key]
    ac_model.load_aircraft(
        weights=load_scheme2, fuel_ltr=fuel, fuel_burn=fuel_burn,
    )

    wandb.print_data(ac_model)

    # save the fig to the image

    fig = wandb.plot_envelope(ac_model)
    plt.text(90, 900, "TEST")
    # create canvas and image
    canvas = FigureCanvas(fig)
    img = io.BytesIO()
    fig.savefig(img)
    img.seek(0)
    return send_file(img, mimetype="img/png", cache_timeout=0)


@views.route("/calculate", methods=["GET", "POST"])
@login_required
def calculate():
    load_scheme = {}
    if request.method == "POST":
        ac_id = request.form.get("ac_id")
        fuel = request.form.get("fuel")
        fuel_burn = request.form.get("fuel_burn")
        will_plot = True

        print("LOAD SCHEME")
        form_data = request.form
        for key in form_data.keys():
            for value in form_data.getlist(key):
                # if key not in ["ac_id", "fuel", "fuel_burn"]:
                if value == "":
                    value = 0
                load_scheme[key] = float(value)
                print(key, ":", value)
    else:
        ac_id = request.args.get("ac_id")
        will_plot = False

    aircraft = Aircraft.query.filter_by(id=ac_id).first()
    loading_points = ast.literal_eval(aircraft.loading_points)

    return render_template(
        "load-aircraft.html",
        aircraft=aircraft,
        user=current_user,
        load_scheme=load_scheme,
        loading_points=loading_points,
        fuel=fuel,
        fuel_burn=fuel_burn,
        will_plot=will_plot,
    )


@views.route("/load-aircraft")
@login_required
def load_aircraft():
    ac_id = request.args.get("ac_id")
    aircraft = Aircraft.query.filter_by(id=ac_id).first()
    loading_points = ast.literal_eval(aircraft.loading_points)
    load_scheme = {}

    return render_template(
        "load-aircraft.html",
        aircraft=aircraft,
        loading_points=loading_points,
        user=current_user,
        load_scheme=load_scheme,
    )


@views.route("/edit-aircraft", methods=["GET", "POST"])
@login_required
def edit_aircraft():
    if request.method == "POST":
        ac_id = request.form.get("ac_id")
        aircraft = Aircraft.query.filter_by(id=ac_id).first()

    form = AircraftForm()

    return render_template(
        "edit_aircraft.html", aircraft=aircraft, form=form, user=current_user
    )


@views.route("/update-aircraft", methods=["POST"])
@login_required
def update_aircraft():
    ac_id = request.form.get("ac_id")
    ac_reg = request.form.get("ac_reg")
    ac_type = request.form.get("ac_type")
    empty_weight = request.form.get("empty_weight").replace(",", ".")
    mtow = request.form.get("mtow").replace(",", ".")
    mlw = request.form.get("mlw").replace(",", ".")
    max_fuel = request.form.get("max_fuel")
    fuel_type = request.form.get("fuel_type")
    envelope = request.form.get("envelope")
    loading_points = request.form.get("loading_points")
    true_airspeed = request.form.get("true_airspeed")
    note = request.form.get("note")

    owned_aircrafts = [x.id for x in current_user.aircrafts]

    if int(ac_id) not in owned_aircrafts:
        flash(
            "You do not own this aircraft and is not allowed to update.",
            category="error",
        )
        aircraft = None
    elif len(ac_reg) < 3:
        flash("Aircraft registration is to short.", category="error")
    else:
        aircraft = db.session.query(Aircraft).filter(Aircraft.id == ac_id).one()
        aircraft.registration = ac_reg
        aircraft.aircraft_type = ac_type
        aircraft.empty_weight = empty_weight
        aircraft.mtow = mtow
        aircraft.mlw = mlw
        aircraft.max_fuel = max_fuel
        aircraft.fuel_type = fuel_type
        aircraft.envelope = envelope
        aircraft.loading_points = loading_points
        aircraft.true_airspeed = true_airspeed
        aircraft.data = note

        db.session.commit()
        flash("Aircraft updated!", category="success")

        aircraft = Aircraft.query.filter_by(id=ac_id).first()
    form = AircraftForm()

    return render_template(
        "edit_aircraft.html", aircraft=aircraft, form=form, user=current_user
    )


@views.route("/add-aircraft", methods=["GET", "POST"])
@login_required
def add_aircraft():
    if request.method == "POST":
        ac_reg = request.form.get("ac_reg")
        ac_type = request.form.get("ac_type")
        empty_weight = request.form.get("empty_weight").replace(",", ".")
        mtow = request.form.get("mtow").replace(",", ".")
        mlw = request.form.get("mlw").replace(",", ".")
        max_fuel = request.form.get("max_fuel")
        fuel_type = request.form.get("fuel_type")
        envelope = request.form.get("envelope")
        loading_points = request.form.get("loading_points")
        true_airspeed = request.form.get("true_airspeed")
        note = request.form.get("note")

        if len(ac_reg) < 3:
            flash("Aircraft registration is to short.", category="error")
        else:
            new_aircraft = Aircraft(
                registration=ac_reg,
                aircraft_type=ac_type,
                empty_weight=empty_weight,
                mtow=mtow,
                mlw=mlw,
                max_fuel=max_fuel,
                fuel_type=fuel_type,
                envelope=envelope,
                loading_points=loading_points,
                true_airspeed=true_airspeed,
                data=note,
                user_id=current_user.id,
            )

            print(fuel_type)
            db.session.add(new_aircraft)
            db.session.commit()
            flash("Aircraft added!", category="success")

        return redirect(url_for("views.home"))
    form = AircraftForm()
    return render_template("add_aircraft.html", form=form, user=current_user)


@views.route("/aircraft-data/<ID>")
def aircraft_data(ID):
    aircraft = Aircraft.query.filter_by(id=ID).first()
    aircraft_dict = {}

    aircraft_dict["loading_points"] = ast.literal_eval(aircraft.loading_points)
    response = jsonify({"aircraft": aircraft_dict})
    response.headers.add("Access-Control-Allow-Origin", "*")

    return response

@views.route("/delete-aircraft", methods=["POST"])
@login_required
def delete_aircraft():
    aircraft = json.loads(request.data)
    aircraftId = aircraft["aircraftId"]
    aircraft = Aircraft.query.get(aircraftId)
    if aircraft:
        if aircraft.user_id == current_user.id or current_user.id == 1:
            db.session.delete(aircraft)
            db.session.commit()

    return jsonify({})

@views.route("/delete-user", methods=["POST"])
@login_required
def delete_user():

    user = json.loads(request.data)
    userId = user["userId"]
    user_to_delete = User.query.get(userId)
    print(user_to_delete)
    if user_to_delete:
        if user_to_delete.id == current_user.id:
            flash("You cannot delete your self at this moment!", category="error")
        else:
            db.session.delete(user_to_delete)
            db.session.commit()
            flash(f"User {user_to_delete.id} is removed", category="success")

    return jsonify({})


@login_required
@views.route("/users")
def users():
    all_users = User.query.order_by(User.id).all()

    return render_template("users.html", user=current_user, all_users=all_users)

website/templates/add_aircraft.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}
{% block content %}
<h1 align="left">Add new aircraft</h1>   
    <form method="POST">
      {{ form.csrf_token() }}
      <br/>
      <h6>Aircraft</h6>
      <div class="row">
        <div class="col-sm-2">
          <div class="form-floating">
            
            {{ form.ac_reg(class="form-control", type="text", id="ac_reg", placeholder="{}") }}
            <label for="ac_reg" class="form-label">{{ form.ac_reg.label }}</label>
          </div>
        </div>
        <div class="col-sm-2">
          <div class="form-floating">
            {{ form.ac_type(class="form-control", type="text", id="ac_type", placeholder="{}") }}
            <label for="ac_type" class="form-label">{{ form.ac_type.label }}</label>
          </div>
        </div>
      </div>
      <br />
      <h6>Weights</h6>
      <div class="row">
        <div class="col-sm-2">
          <div class="form-floating">
            
            {{ form.empty_weight(class="form-control", type="text", id="empty_weight", placeholder="{}") }}
            <label for="empty_weight" class="form-label">{{ form.empty_weight.label }}</label>
          </div>
        </div>
        <div class="col-sm-2">
          <div class="form-floating">
            {{ form.mtow(class="form-control", type="text", id="mtow", placeholder="{}") }}
            <label for="mtow" class="form-label">{{ form.mtow.label }}</label>
          </div>
        </div>
        <div class="col-sm-2">
          <div class="form-floating">
            {{ form.mlw(class="form-control", type="text", id="mlw", placeholder="{}") }}
            <label for="mlw" class="form-label">{{ form.mlw.label }}</label>
          </div>
        </div>
      </div>
      <br />
      <h6>Fuel</h6>
      <div class="row">
        <div class="col-sm-2">
          <div class="form-floating">
            
            {{ form.max_fuel(class="form-control", type="text", id="max_fuel", placeholder="{}") }}
            <label for="max_fuel" class="form-label">{{ form.max_fuel.label }}</label>
          </div>
        </div>
        <div class="col-sm-2">
          <!-- {{ form.fuel_type(class="btn btn-outline-secondary", type="radio", id="fuel_type_jet", autocomplete="off", checked=true) }} -->
          <input type="radio" class="btn-check" name="fuel_type" id="fuel_type_jet" value="jet" autocomplete="off" checked>
          <label class="btn btn-outline-secondary" for="fuel_type_jet">Jet A1</label>

          <input type="radio" class="btn-check" name="fuel_type" id="fuel_type_avgas" value="avgas" autocomplete="off">
          <label class="btn btn-outline-danger" for="fuel_type_avgas">Avgas</label>
        </div>
      </div>
      <br />
      <!-- ADD ENVELOPE BUTTONS -->
      <h6>Weight and Balance</h6>
      <div class="row">
        <div class="row mb-4">
          <div class="col-sm-3">
            <button type="button" class="btn btn-sm btn-primary" data-bs-toggle="modal" data-bs-target="#envelopeModal">
              Add Envelope Point
            </button>
            <button type="button" class="btn btn-sm btn-warning" onclick="clearEnvelope()">
              Clear Envelope
            </button>
          </div>
        </div>
    </div>
    <!-- END OF ENVELOPE BUTTONS -->
      <div class="row">
        <div class="col-sm-6">
          <div class="form-floating">
            
            {{ form.envelope(class="form-control", type="text", id="envelope", placeholder="{}", readonly=readonly) }}
            <label for="envelope" class="form-label">{{ form.envelope.label }}</label>
          </div>
        </div>
      </div>
        <!-- ADD LOAD POINT BUTTONS -->
        <br/>
        <h6>Load Points</h6>
        <div class="row">
            <div class="row mb-4">
              <div class="col-sm-3">
                <button type="button" class="btn btn-sm btn-primary" data-bs-toggle="modal" data-bs-target="#loadpointModal">
                  Add New Load Point
                </button>
                <button type="button" class="btn btn-sm btn-warning" onclick="clearLoadpoints()">
                  Clear Loading Points
                </button>
              </div>
            </div>
        </div>
        <!-- END OF LOAD POINT BUTTONS -->
        <div class="col-sm-6">
          <div class="form-floating">
            
            {{ form.loading_points(class="form-control", type="text", id="loading_points", placeholder="{}", readonly=readonly) }}
            <label for="loading_points" class="form-label">{{ form.loading_points.label }}</label>
          </div>
        </div>

      <br />
      <h6>Speed</h6>
      <div class="row">
        <div class="col-sm-2">
          <div class="form-floating">
            
            {{ form.true_airspeed(class="form-control", type="text", id="true_airspeed", placeholder="{}") }}
            <label for="true_airspeed" class="form-label">{{ form.true_airspeed.label }}</label>
          </div>
        </div>
      </div>
      <br />
      <h6>Additional Data</h6>
      <div class="row">
        <div class="col-sm-8">
          <div class="form-floating">
            
            {{ form.note(class="form-control", type="text", id="note", placeholder="{}") }}
            <label for="note" class="form-label">{{ form.data.label }}</label>
          </div>
        </div>
      </div>
      <br />
      <div align="left">
        <a href="{{ url_for("views.home") }}" class="btn btn-primary">Back</a>
        <button type="submit" class="btn btn-primary">Add Aircraft</button>
      </div>
    </form>

     <!-- THE ENVELOPE MODAL DIALOG -->

     <div class="modal fade-scale" id="envelopeModal" role="dialog" data-backdrop="static" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
          <div class="modal-content">
              <div class="modal-header">
                  <h4 class="modal-title">Add Envelope Points</h4>
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body">
                  <form id="envelopeForm" name="envelopeForm">
                      <input type="hidden" name="id" id="id" value="0">
                      <div class="row">
                          <div class="col-sm-12">
                              <div class="form-group">
                                  <label >Weight Limit</label>
                                  <input class="form-control" placeholder="Weight" name="weight" id="weight" type="text" value="">
                              </div>
                          </div>
                          <div class="col-sm-12">
                              <div class="form-group">
                                  <label >CG Distance from datum</label>
                                  <input class="form-control" placeholder="CG Distance" name="cg_envelope" id="cg_envelope" type="text" value="">
                              </div>
                          </div>
                      </div>
                  </form>
                  <br />
                  <div class="container">
                    <div class="row justify-content-md-center text-center">
                      <div class="col md-auto bg-light">
                        Values are needed for at least 4 points<br/>
                        added in clockwise or counter clockwise order.
                      </div>
                    </div>
                  </div>

              </div>
              <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                  <button type="button" class="btn btn-primary" id="saveEnvelope">Save</button>
              </div>
          </div>
      </div>
  </div>

  <!-- END OF ENVELOPE MODAL DIALOG -->





    <!-- THE LOAD POINT MODAL DIALOG -->

    <div class="modal fade-scale" id="loadpointModal" role="dialog" data-backdrop="static" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
          <div class="modal-content">
              <div class="modal-header">
                  <h4 class="modal-title">Add New Load Point</h4>
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body">
                  <form id="loadpointForm" name="loadpointForm">
                      <input type="hidden" name="id" id="id" value="0">
                      <div class="row">
                          <div class="col-sm-12">
                              <div class="form-group">
                                  <label >Name</label>
                                  <input class="form-control" placeholder="Name" name="name" id="name" type="text" value="">
                              </div>
                          </div>
                          <div class="col-sm-12">
                              <div class="form-group">
                                  <label >CG Distance from datum</label>
                                  <input class="form-control" placeholder="CG Distance" name="cg_distance" id="cg_distance" type="text" value="">
                              </div>
                          </div>
                      </div>
                  </form>
                  <br />
                  <div class="container">
                    <div class="row justify-content-md-center text-center">
                      <div class="col md-auto bg-light">
                        Values for at least the points<br/>
                        <b>"empty_weight", "pilot" and "fuel"</b><br/>
                        are needed for calculations.<br/>
                      </div>
                    </div>
                    <div class="row text-center">
                      <div class="col md-auto bg-danger">
                        If not added they will be added at zero distance.
                      </div>
                    </div>
                    
                  </div>

              </div>
              <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                  <button type="button" class="btn btn-primary" id="saveLoadpoint">Save</button>
              </div>
          </div>
      </div>
  </div>

  <!-- END OF LOAD POINT MODAL DIALOG -->

{% endblock %}

website/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" type="text/css" href="static/custom.css">

    <title>{% block title %}Home{% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
      <button
        class="navbar-toggler"
        type="button"
        data-bs-toggle="collapse"
        data-bs-target="#navbar"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar">
        <div class="navbar-nav">
          {% if user.is_authenticated %}
          <a class="nav-item nav-link" id="home" href="/">Home</a>
          {% if user.id == 1 %}
            <a class="nav-item nav-link" id="users" href="{{ url_for("views.users") }}">Users</a>
          {% endif %}
        </div>
        <div class="navbar-nav ms-auto">
          <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
          <a class="nav-item nav-link" id="profile" href="{{ url_for("user_views.profile")}}">{{ user.first_name }}</a>
          {% else %}
          <a class="nav-item nav-link" id="login" href="/login">Login</a>
          <a class="nav-item nav-link" id="signUp" href="/sign-up">Sign Up</a>
          {% endif %}
        </div>
      </div>
    </nav>

    {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %} 
        {% for category, message in messages %}
          {% if category == 'error' %}
          <div class="alert alert-danger alter-dismissable fade show" role="alert">
            {{ message }}
            <button type="button" class="btn-close" aria-label="Close" aria-hidden="true" data-bs-dismiss="alert">
              
            </button>
          </div>
          {% else %}
          <div class="alert alert-success alter-dismissable fade show" role="alert">
            {{ message }}
            <button type="button" class="btn-close" aria-label="Close" aria-hidden="true" data-bs-dismiss="alert">
              
            </button>
          </div>
          {% endif %}
        {% endfor %}
      {% endif %}
    {% endwith %}

    <div class="container">{% block content %} {% endblock %}</div>
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script 
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"
      crossorigin="anonymous"
    ></script>

    <script
      type="text/javascript"
      src="{{ url_for('static', filename='index.js') }}"
    ></script>
    
  </body>
</html>

website/templates/home.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}
{% block content %}
    <h1 align="left">Aircrafts</h1>
    <table class="table table-striped">
      <thead>
        <tr>
          <th scope="col">ID</th>
          {% if user.id == 1 %}
          <th scope="col">OWNER</th>
          {% endif %}
          <th scope="col">REG</th>
          <th scope="col">TYPE</th>
          <th scope="col">FUEL</th>
          <th scope="col">NOTES</th>
          <th scope="col"></th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        {% for aircraft in aircrafts %}
        <tr>
          <th scope="row">{{ aircraft.id }}</th>
          {% if user.id == 1 %}
          <td>{{ aircraft.user_id }}</td>
          {% endif %}
          <td>{{ aircraft.registration }}</td>
          <td>{{ aircraft.aircraft_type }}</td>
          <td>{{ aircraft.fuel_type.upper() }}</td>
          <td>{{ aircraft.data }}</td>
          <td>
            <a href="{{ url_for("views.load_aircraft", ac_id=aircraft.id) }}" class="btn btn-primary pull-right">Calculate</a>
          </td>
          <td>
            {% if aircraft.user_id == user.id or user.id == 1 %}
            <form method="POST" action="edit-aircraft">
              {{ form.csrf_token() }}
              <input type="hidden" id="ac_id" name="ac_id" value="{{ aircraft.id }}"/>
              <button type="submit" action="edit-aircraft" class="btn btn-warning" aria-label="Edit">
                Edit
              </button>
              <button type="button" class="btn btn-danger pull-right" aria-label="Delete" onClick="deleteAircraft({{ aircraft.id }})">
                Delete
              </button>
            </form>
            {% else %}
          </td>
          
          {% endif %}
        </tr>
        {% endfor %}
      </tbody>
    
    </table>
    <br />
    <br />

    <a href="{{ url_for("views.add_aircraft") }}" type="button" class="btn btn-primary" aria-label="Add aircraft">Add Aircraft</a>
    

    {% endblock %}

website/templates/load-aircraft.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}
{% block content %}

<h1 align="left">Load aircraft</h1>


<form method="POST" action="calculate">
<!-- <form method="POST"> -->
    
    {% for lp in loading_points %}
    
    {% if not lp == "empty_weight" %}
        <div class="row">
            <div class="col-sm-4">
                <div class="form-floating">
                    <input type="text" class="form-control" name="{{ lp }}" id="{{ lp }}" placeholder="{{ lp }}" value="{{ load_scheme[lp] }}">
                    <label for="{{ lp }}" class="form-label">{{ lp.replace("_", " ").capitalize() }} {% if lp == "fuel" %} (l) {% endif %}</label>
                </div>
            </div>
        </div>
    {% endif %}
    {% endfor %}
    <div class="row">
        <div class="col-sm-4">
            <div class="form-floating">
                <input type="text" class="form-control" name="fuel_burn" id="fuel_burn" placeholder="Fuel Burn" value="{{ fuel_burn }}">
                <label for="fuel_burn" class="form-label">Expected Fuel Burn (l)</label>
            </div>
        </div>
    </div>

<div class="col-sm-2">
    <a href="{{ url_for("views.home") }}" class="btn btn-primary">Back</a>
    <input type="hidden" id="ac_id" name="ac_id" value="{{ aircraft.id }}"/>
    <button type="submit" onclick="getImage({{ url_for("views.plot", ac_id=aircraft.id, load_scheme=load_scheme, fuel=fuel, fuel_burn=fuel_burn) }})" class="btn btn-primary" aria-label="Calculate">
        Calculate
    </button>
</div>
</form>
{% if will_plot == True %}


<div class="d-flex justify-content-center">
    <div class="spinner-border text-primary" 
        id="spinner" role="status"> 
        <span class="sr-only">Loading...</span> 
    </div> 
    <img src="{{ url_for("views.plot", ac_id=aircraft.id, load_scheme=load_scheme, fuel=fuel, fuel_burn=fuel_burn) }}" class="img-fluid" alt="weight and balance plot" onload="hideSpinner()">
</div>

{% endif %}
{% endblock %}

website/templates/login.html
{% extends "base.html" %} {% block title %}Login{% endblock %} {% block content
    %}
    <form method="POST">
      <h3 align="center">Login</h3>
      <div class="form-group">
        <label for="email">Email Address</label>
        <input
          type="email"
          class="form-control"
          id="email"
          name="email"
          placeholder="Enter email"
        />
      </div>
      <div class="form-group">
        <label for="password">Password</label>
        <input
          type="password"
          class="form-control"
          id="password"
          name="password"
          placeholder="Enter password"
        />
      </div>
      <br />
      <button type="submit" class="btn btn-primary">Login</button>
    </form>
    {% endblock %}

website/templates/profile.html
{% extends "base.html"%}
{% block title %}
User Profile
{% endblock %}
{% block content %}
<h3 align="left">{{ user.first_name }}</h3>

<form action="update-user" method="POST">

        <div class="row">
            <div class="col-sm-4">
                <div class="form-floating mb-3">
                    <input class="form-control" type="text" name="first_name" id="first_name" value={{ user.first_name }}>
                    <label for="first_name" class="form-label">First Name</label>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-4">    
                <div class="form-floating mb-3">
                    <input class="form-control" type="text" name="last_name" id="last_name" value={{ user.last_name }}>
                    <label for="last_name" class="form-label">Last Name</label>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-4">    
                <div class="form-floating mb-3">
                    <input class="form-control" type="text" name="email" id="email" value={{ user.email }}>
                    <label for="email" class="form-label">E-mail</label>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-4">    
                <div class="form-floating mb-3">
                    <input class="form-control" type="password" name="password1" id="password1" placeholder="Password">
                    <label for="password1" class="form-label">Password</label>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-4">    
                <div class="form-floating mb-3">
                    <input class="form-control" type="password" name="password2" id="password2" placeholder="Confirm Password">
                    <label for="password2" class="form-label">Confirm Password</label>
                </div>
            </div>
        </div>
        <input type="hidden" id="user_id" name="user_id" value="{{ user.id }}"/>
        <button type="submit" class="btn btn-warning" aria-label="Update">
            Update User
        </button>
    
</form>

{% endblock %}